services:
  api:
    container_name: smena-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    expose:
      - "5000"
      - "5001"
    networks:
      - smena_edge
    # Остальные настройки читаются из appsettings.*.json

networks:
  smena_edge:
    name: smena_edge
    external: true
