services:
  api:
    container_name: smena-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    # Остальные настройки читаются из appsettings.*.json
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
    driver: bridge
